### ISSUE TITLE
500 Failed to lookup view "index" 

### ISSUE THREAD

**Issue by elieobeid7** [Silvenga/Slight-Theme#3]
Hi, I'm getting this error, do you know why?

500
Failed to lookup view "index" in views directory "/home/elie/projects/websites/Ghost (backup)/content/themes/Slight-Theme-Dev"

Cheers and Merry Christmas!

**Comment by bgp92** [comment]
I am getting the same as well, same ghost version and all. Hoping for the reply.
Best regards

**Comment by Silvenga** [comment]
I feel like Github should send me emails on issues. I've got to fix that. 

@elieobeid7 @bgp92 sorry for the depay. Make sure that the `Slight` folder is at the root of the `themes` directory. It should look like:

```
themes/
-- Slight/
---- assets/
---- index.hbs
---- etc....
```

**Comment by bgp92** [comment]
Yup, thanks for the support btw :)

**Comment by Silvenga** [comment]
@bgp92, I totally didn't recognize your username yesterday. I'm going to close this issue, @elieobeid7 if you still have issues please comment here for a reopen.
